- name: Build and deploy application
  hosts: all
  # connection: local

  vars:
    docker_image_name: "solaris"
    home: "../.."
    HOME: "/tmp/solaris"
  tasks:
    - name: Clear path
      file:
        state: "absent"
        path: "{{ HOME }}/"
    - name: Checkout from git
      git:
        repo: 'git@github.com:sscheffler/solaris.git'
        dest: '{{ HOME }}'
        version: master

    # - name: Pull latest from git
    #   command: "git pull origin master"

    #- name: Install dependent python modules
    #  pip:
    #    name: "{{item}}"
    #    state: present
    #  with_items:
    #    - docker-py==1.10.6
    #    - docker-compose==1.9.0

    - name: Build artifact
      command: "mvn clean install -f {{ HOME }}/pom.xml -Ddockerfile.build.skip=true"

    - name: Build docker image
      command: "mvn dockerfile:build -f {{ HOME }}/pom.xml"

    - name: Mongo Container present
      docker_container:
        name: "mongo"
        image: "tutum/mongodb"
        state: started
        exposed_ports:
         - "27017:27017"

    - name: Solaris Container
      docker_container:
        name: "{{ docker_image_name }}"
        image: "solarsystem/solaris:latest"
        recreate: "yes"
        ports:
          - "8100:8080"
        links:
          - "mongo:mongo"




    #- name: Stop docker image
    #  command: "docker stop {{ imagae_name }}"
    #
    #- name: Remove image
    #  command